libgpgerror: fix cross-compilation
Backporting a fix (merged upstream but no release cut) for shell quoting issues

(cherry picked from commit 6042dd28cfba1dc948b5d601052c8ecd1584cd91)