Revert "notmuch: 0.32.1 -> 0.32.2; clarify license"
This reverts commit 15eec2111fc06cca2b0abd7b3de1b6922fabf21e.

This breaks python-notmuch package:
error: builder for '/nix/store/wf2fxcs8233cqr49ab2hqzd5zm428ij4-python3.9-notmuch-0.32.2.drv'
failed with exit code 1;
       last 10 log lines:
       > Using setuptoolsShellHook
       > Sourcing pip-install-hook
       > Using pipInstallPhase
       > Sourcing python-imports-check-hook.sh
       > Using pythonImportsCheckPhase
       > Sourcing python-namespaces-hook
       > unpacking sources
       > unpacking source archive /nix/store/5wkym9dc58531l643vnvni4id9d0i5xy-notmuch-0.32.2.tar.xz
       > source root is notmuch-0.32.2.tar.xz/bindings/python
       > chmod: cannot access 'notmuch-0.32.2.tar.xz/bindings/python': No such file or directory
       For full logs, run 'nix log /nix/store/wf2fxcs8233cqr49ab2hqzd5zm428ij4-python3.9-notmuch-0.32.2.drv'.